export const tableData = [
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Delisted',
  },
  {
    id: 65658,
    dateRemoved: '23 Sep 2023',
    link: 'https://google. com',
    source: 'Reddit',
    action: 'Removed',
  },
];
